done
Xoyk23/node-hw01 pull request #1
Opened 2021-05-03 12:18 UTC by Xoyk23

2021-05-03 20:09 UTC, SergeiKBB requested changes

2021-05-03 20:09 UTC, SergeiKBB commented on contacts.js
> +      const contact = contacts.find((contact) => contact.id == contactId);
Решил не приводить contactId к числу, вместо этого использовать не строгое равенство?)

2021-05-03 20:09 UTC, SergeiKBB commented on contacts.js
> +      const contact = contacts.find((contact) => contact.id == contactId);
P.S. на проекта настроены линтеры, которые ругаются на нестрогое равенство...

2021-05-03 20:09 UTC, SergeiKBB commented on contacts.js
> +      fs.writeFile(contactsPath, JSON.stringify(contactsFiltered, null, "\t"));
Добавь проверку что ты точно удалил контакт с таким айди. Может быть ситуация, когда у тебя просто не будет контакта с таким айди и тебе все равно прийдется перезаписывать файл, хотя в этом нет нужды

2021-05-03 20:09 UTC, SergeiKBB commented on contacts.js
> +      console.log("Added");
Не коректный лог, так как он выведется до того как контакт добавится (fs.writeFile - асинхроный метод)

2021-05-04 06:19 UTC, Xoyk23 commented on contacts.js
> +      fs.writeFile(contactsPath, JSON.stringify(contactsFiltered, null, "\t"));
Сделано!

2021-05-04 17:57 UTC, SergeiKBB approved these changes

2021-05-04 19:16 UTC, merged